### ISSUE TITLE
readDrawable function error

### ISSUE THREAD

**Issue by javadi69** [adivery/adivery-flutter-plugin#1]
Hello,
We have a crash report spiking in Firebase, Please investigate the issue,
Thank you,

Flutter version: 2.5.3
Adivery version: 4.0.5

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap android.graphics.drawable.BitmapDrawable.getBitmap()' on a null object reference
>        at com.adivery.plugin.NativeAd.readDrawable(NativeAd.java:95)
>        at com.adivery.plugin.NativeAd.access$200(NativeAd.java:20)
>        at com.adivery.plugin.NativeAd$1.onAdLoaded(NativeAd.java:57)
>        at com.adivery.sdk.z$a.run(z.java:8)
>        at android.os.Handler.handleCallback(Handler.java:809)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:166)
>        at android.app.ActivityThread.main(ActivityThread.java:7555)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by shayan4shayan** [comment]
Thanks for your report
could you please give me the steps to reproduce this Error?

**Comment by javadi69** [comment]
It seems to be fixed in the latest version as we didn't have any report on this, lately.
