### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by javadi69** [adivery/adivery-flutter-plugin#2]
Hello,
Please investigate this issue,
Thanks,

> Fatal Exception: java.lang.NullPointerException
>        at com.adivery.sdk.t0.c(t0.java:2)
>        at com.adivery.sdk.t0.g(t0.java:1)
>        at com.adivery.sdk.t0$d.a(t0.java:894)
>        at com.adivery.sdk.t0$d.a(t0.java:864)
>        at com.adivery.sdk.t0$d.a(t0.java:846)
>        at com.adivery.sdk.t0$d.a(t0.java:838)
>        at com.adivery.sdk.u0.d(u0.java:16)
>        at com.adivery.sdk.-$$Lambda$twNpH3olvQcb8ulgoMi9JPFqHhA.run(-.java:2)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:246)
>        at android.app.ActivityThread.main(ActivityThread.java:8653)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Flutter version: 3.0.0
Adivery: 4.2.10

**Comment by shayan4shayan** [comment]
Version 4.3.0 was published just now to fix this issue
Please re-open the issue if the problem exists.
